version: '3'
services:
  db:
    container_name: db
    image: linuxserver/mariadb:alpine
    environment:
      - MYSQL_DATABASE=budget
      - MYSQL_USER=budget-keeper
      - MYSQL_PASSWORD=123Budget#
    volumes:
      - "./sql/init:/docker-entrypoint-initdb.d/"
    networks:
      - app-test
    expose:
      - 3006
    ports:
      - "3006:3006"
  api:
    container_name: api
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - app-test
    depends_on:
      - db
  react-ui:
    container_name: ui
    build:
      context: ./app
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-test
networks:
  app-test:
    driver: bridge

