version: '3'
services:
  api:
    container_name: api
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - app-test
  react-ui:
    container_name: ui
    build:
      context: ./app
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-test
networks:
  app-test:
    driver: bridge

