version: '3'
services:
  api:
    restart: always
    container_name: api
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - budget-net
  react-ui:
    restart: always
    container_name: ui
    build:
      context: ./app
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - budget-net
networks:
  budget-net:
    external: true
