buildscript {
    repositories {
        gradlePluginPortal()
    }

    dependencies {
        classpath "com.github.node-gradle:gradle-node-plugin:7.0.2"
    }
}

apply plugin: 'com.github.node-gradle.node'

node {
    download = true
    version = "20.19.0"
}

tasks.register('npmBuild', NpmTask) {
    args = [ 'run', 'build' ]
}